Repository JeffKersting/crate-1, pull requests merged in 2021-04, with the labels that each got.

#21 Graphql test
  code/api/package-lock.json
  code/api/package.json
  code/api/src/.env.local
  code/api/src/config/database.json
  code/api/src/modules/style/tests/styleQuery.test.js
  code/api/src/modules/user/tests/updateTest.test.js
Labels: Backend

#22 Jk feature submit style
  code/web/src/modules/crate/Item.js
  code/web/src/modules/user/Survey.js
  code/web/src/modules/user/api/actions.js
Labels: Frontend, enhancement

#23 Add styling to the style survey
  code/api/package-lock.json
  code/web/src/modules/survey/Item.js
  code/web/src/modules/survey/List.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/Survey.js
  code/web/src/ui/card/Card.js
Labels: Frontend, enhancement

#25 Docs
  README.md
Labels: documentation

#26 Add action jest test
  code/package-lock.json
  code/package.json
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/.DS_Store
  code/web/src/modules/user/api/tests/userStyle.test.js
Labels: Frontend, testing
