Repository JeffKersting/crate-1, pull requests merged in 2021-03, with the labels that each got.

#12 Style schema
  .gitignore
  code/api/.gitignore
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/migrations/1-user.js
  code/api/src/migrations/5-styles.js
  code/api/src/modules/style/model.js
  code/api/src/seeders/4-styles.js
  code/api/src/setup/models.js
  code/package-lock.json
Labels: Backend

#13 Style add type column
  code/api/src/migrations/5-styles.js
  code/api/src/modules/style/model.js
  code/api/src/seeders/4-styles.js
Labels: Backend, enhancement

#18 Cma/feature/survey component
  code/api/.gitignore
  code/api/public/images/survey/man.png
  code/api/public/images/survey/unisex.png
  code/api/public/images/survey/woman.png
  code/api/src/config/database.json
  code/api/src/migrations/5-styles.js
  code/api/src/modules/style/model.js
  code/api/src/seeders/4-styles.js
  code/web/src/modules/crate/Item.js
  code/web/src/modules/survey/Item.js
  code/web/src/modules/survey/List.js
  code/web/src/modules/survey/genderPreferences.js
  code/web/src/modules/user/Survey.js
  code/web/src/setup/routes/user.js
  code/web/src/ui/image/Tile.js
Labels: Frontend, enhancement

#20 Update Survey functionality, and survey logic
  code/api/package-lock.json
  code/api/public/images/survey/casual-accessories-mens.jpg
  code/api/public/images/survey/casual-pants-men.jpg
  code/api/public/images/survey/casual-pants-women.jpg
  code/api/public/images/survey/casual-shirts-mens.jpg
  code/api/public/images/survey/casual-shirts-women.jpg
  code/api/public/images/survey/casual-shoes-women.jpg
  code/api/public/images/survey/edgy-accessory-mens.jpg
  code/api/public/images/survey/edgy-accessory-womens.jpg
  code/api/public/images/survey/edgy-pants-mens.jpg
  code/api/public/images/survey/edgy-shirt-mens.jpg
  code/api/public/images/survey/edgy-shoes-womens.jpg
  code/api/public/images/survey/street-accessories-mens.jpg
  code/api/public/images/survey/street-accessories-women.jpg
  code/api/public/images/survey/street-pants-mens.jpg
  code/api/public/images/survey/street-pants-women.jpg
  code/api/public/images/survey/street-shirt-mens.jpg
  code/api/public/images/survey/street-shirt-women.jpg
  code/api/public/images/survey/street-shoe-men.jpg
  code/api/public/images/survey/street-shoe-women.jpg
  code/api/src/config/database.json
  code/web/src/modules/survey/Item.js
  code/web/src/modules/survey/List.js
  code/web/src/modules/user/Survey.js
  code/web/src/modules/user/api/actions.js
Labels: Frontend, enhancement
